name: coodart
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1535618775524199
title: coodart grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d5c6c'
    - '#a4cc89'
    - '#f6f6f6'
    - '#f18074'
    - '#8c959f'
  brandStrength: 0.5
  lightness: 0.641753364354372
  saturation: 0.49607479595579207
  rhythmicContrast: 0.742380820447579
purpose: []
